# Generated by Django 3.2.11 on 2022-01-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='alias',
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=9223372036854775807),
        ),
    ]
